name: Test and Pypi
# Tests and publishes to live pypi
# Runs on every git tag

on:
  push:
    tags:        
      - '*'

jobs:

  codecov:
    uses: fptiangco/github-actions-workflows/.github/workflows/test_codecov.yml@main
    secrets:
       codecovtoken: ${{ secrets.CODECOV_TOKEN }}

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  build:
    needs: [ codecov, black ]
    uses: fptiangco/github-actions-workflows/.github/workflows/build_publish_pypi.yml@main
    with:
      twine_repository: pypi
    secrets:
       twine_token: ${{ secrets.TWINE_TOKEN }}