name: Publish to Test Pypi
# Publishes to test pypi
# Needs manual workflow dispatch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    uses: fptiangco/github-actions-workflows/.github/workflows/build_publish_pypi.yml@main
    with:
      twine_repository: testpypi
    secrets:
       twine_token: ${{ secrets.TWINE_TEST_TOKEN }}